In [31]:
import numpy as np
X_train = np.array([[ 1., -1.,  2.], [ 2.,  0.,  0.], [ 0.,  1., -1.]])

In [32]:
# Take the original column (feature), subtract the mean and divide by the standard deviation
# Python lists will make the columns into rows, we'll deal with that later
a =(X_train[:,0] - X_train[:,0].mean()) / X_train[:,0].std()
b =(X_train[:,1] - X_train[:,1].mean()) / X_train[:,1].std()
c =(X_train[:,2] - X_train[:,2].mean()) / X_train[:,2].std()

# a, b, c

In [33]:
a_b_c = (X_train - X_train.mean(axis = 0)) / X_train.std(axis = 0)
a_b_c

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [34]:
# Invert the columns and the rows to make the data match the input
np.transpose(a_b_c)
# Another way to do it
# np.c_(a_b_c)

array([[ 0.        ,  1.22474487, -1.22474487],
       [-1.22474487,  0.        ,  1.22474487],
       [ 1.33630621, -0.26726124, -1.06904497]])

In [35]:
from sklearn import preprocessing 

In [36]:
# another way to do what we did above using sklearn
X_scaled = preprocessing.scale(X_train)
X_scaled 

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [37]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [38]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [39]:
# another way to do the same thing
scaler = preprocessing.StandardScalar().fit(X_train)
scaler

AttributeError: module 'sklearn.preprocessing' has no attribute 'StandardScalar'